In [2]:
from dotenv import load_dotenv
import os
import time  # <--- agrega esta línea
import json
import requests

# Ruta .env en la raíz del repo
env_path = os.path.abspath(os.path.join(os.getcwd(), "../../..", ".env"))
load_dotenv(dotenv_path=env_path)

# Obtener clave de Grok desde .env
GROK_API_KEY = os.getenv("GROK_API_KEY")

if GROK_API_KEY:
    print("Clave de Grok cargada correctamente.")
else:
    raise ValueError("❌ No se encontró la clave de Grok. Verifica la ruta del .env.")

Clave de Grok cargada correctamente.

In [4]:
def call_grok_api(prompt, text):
    """
    Envía un texto y un prompt al modelo Grok-4 y devuelve el resumen generado.
    """
    url = "https://api.x.ai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {GROK_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "grok-4",
        "messages": [
            {"role": "system", "content": "Eres un asistente experto en simplificar lenguaje biomédico."},
            {"role": "user", "content": f"{prompt}\n\nTexto:\n{text}"}
        ]
    }

    try:
        start_time = time.time()
        response = requests.post(url, headers=headers, json=payload)
        elapsed = time.time() - start_time

        # Mostrar más información si algo falla
        print(f"Código de estado: {response.status_code}")
        try:
            print("Respuesta (primeros 200 caracteres):", response.text[:200])
        except Exception as e:
            print("No se pudo imprimir el texto:", e)

        if response.status_code == 200:
            data = response.json()
            # Muestra las claves del JSON
            print("Claves en respuesta:", data.keys())
            output = data["choices"][0]["message"]["content"]
            return output.strip(), elapsed
        else:
            print(f"Error HTTP {response.status_code}: {response.text}")
            return None, elapsed
    except Exception as e:
        print("Error en la solicitud:", e)
        return None, None

In [5]:
import pandas as pd
#traemos el archivo test.csv
ruta_dataset = "../data-sources/pre-processed/data_finetuning_test.csv"
df = pd.read_csv(ruta_dataset, encoding="utf-8", on_bad_lines="skip")
display(df.head(2))

,name,article,summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...

In [6]:
# Prompt a utilizarse
prompt = """Using the following abstract of a biomedical study as input, generate a Plain Language Summary (PLS) understandable by any patient, regardless of their health literacy. Ensure that the generated text adheres to the following instructions which should be followed step-by-step:
    a. Specific Structure: the generated PLS should be presented in a logical order, using the following order:
        1. Plain Title
        2. Rationale
        3. Trial Design
        4. Results
    b. Sections should be authored following these parameters:
        1. Plain Title: Simplified title understandable to a layperson that summarizes the research that was done.
        2. Rationale: Include: background or study rationale providing a general description of the condition, what it may cause or why it is a burden for the patients; the reason and main hypothesis for the study; and why the study is needed, and why the study medication has the potential to treat the condition.
        3. Trial Design: Answer ‘How is this study designed?’ Include the description of the design, description of study and patient population (age, health condition, genre), and the expected amount of time a person will be in the study.
        4. Results: answer ‘What were the main results of the study’, include what are the benefits for the patients, how the study was relevant for the area of study, and what are the conclusions from the investigator.
    c. Consistency and Replicability: the generated PLS should be consistent regardless of the order of sentences or the specific phrasing used in the input protocol text.
    d. Compliance with Plain Language Guidelines: The generated PLS must follow all of these plain language guidelines:
        1. Have readability grade level of 6 or below.
        2. Do not have jargon. All technical or medical words or terms should be defined or broken down into simple and logical explanations.
        3. Active voice, not passive
        4. Mostly one or two syllable words
        5. Sentences of 15 words or less
        6. Short paragraphs of 3-5 sentences
        7. Simple numbers (eg, ratios, no percentages)
    e. Do not invent Content: The AI model should not invent information. If the AI model includes data other than the one given in the input abstract, the AI model should guarantee such data is verified and real.
    f. Aim for an approximate PLS length of 500-900 words.

    Abstract of a biomedical study text:Using the following abstract of a biomedical study as input, generate a Plain Language Summary (PLS) understandable by any patient, regardless of their health literacy. Ensure that the generated text adheres to the following instructions which should be followed step-by-step:
    a. Specific Structure: the generated PLS should be presented in a logical order, using the following order:
        1. Plain Title
        2. Rationale
        3. Trial Design
        4. Results
    b. Sections should be authored following these parameters:
        1. Plain Title: Simplified title understandable to a layperson that summarizes the research that was done.
        2. Rationale: Include: background or study rationale providing a general description of the condition, what it may cause or why it is a burden for the patients; the reason and main hypothesis for the study; and why the study is needed, and why the study medication has the potential to treat the condition.
        3. Trial Design: Answer ‘How is this study designed?’ Include the description of the design, description of study and patient population (age, health condition, genre), and the expected amount of time a person will be in the study.
        4. Results: answer ‘What were the main results of the study’, include what are the benefits for the patients, how the study was relevant for the area of study, and what are the conclusions from the investigator.
    c. Consistency and Replicability: the generated PLS should be consistent regardless of the order of sentences or the specific phrasing used in the input protocol text.
    d. Compliance with Plain Language Guidelines: The generated PLS must follow all of these plain language guidelines:
        1. Have readability grade level of 6 or below.
        2. Do not have jargon. All technical or medical words or terms should be defined or broken down into simple and logical explanations.
        3. Active voice, not passive
        4. Mostly one or two syllable words
        5. Sentences of 15 words or less
        6. Short paragraphs of 3-5 sentences
        7. Simple numbers (eg, ratios, no percentages)
    e. Do not invent Content: The AI model should not invent information. If the AI model includes data other than the one given in the input abstract, the AI model should guarantee such data is verified and real.
    f. Aim for an approximate PLS length of 500-900 words."""

# Tomar las dos primeras filas para prueba inicial
#df_prueba = df.head(2).copy()

# Lista donde guardaremos los resúmenes generados de la prueba
#gen_summaries = []

#for i, fila in df_prueba.iterrows():
#    print(f"\n Procesando {fila['name']} ({i+1}/{len(df_prueba)})...\n")
#    resumen, tiempo = call_grok_api(prompt, fila['article'])
#    gen_summaries.append(resumen if resumen else "")
#    print(f"Tiempo de respuesta: {tiempo:.2f} s\n")

# Añadir columna con los resúmenes generados
#df_prueba["gen_summary"] = gen_summaries

# Guardar en CSV la prueba
#ruta_salida = "./resultados_grok.csv"
#df_prueba.to_csv(ruta_salida, index=False, encoding="utf-8")

#print(f"Resultados guardados en: {os.path.abspath(ruta_salida)}")
#display(df_prueba)

In [5]:
#Aca vamos a usar todo el dataset
df_groktest = df.copy()

# Lista donde guardaremos los resúmenes generados
gen_summaries = []

# Contador de tiempo total
inicio_total = time.time()

for i, fila in df_groktest.iterrows():
    print(f"\n Procesando {fila['name']} ({i+1}/{len(df_groktest)})...\n")
    resumen, tiempo = call_grok_api(prompt, fila['article'])
    gen_summaries.append(resumen if resumen else "")
    print(f" Tiempo de respuesta: {tiempo:.2f} s\n")

# Añadir columna con los resúmenes generados
df_groktest["gen_summary"] = gen_summaries

# Guardar resultados
ruta_salida = "./results_grok2.csv"
df_groktest.to_csv(ruta_salida, index=False, encoding="utf-8")

duracion_total = time.time() - inicio_total
print(f"Resultados guardados en: {os.path.abspath(ruta_salida)}")
print(f"Tiempo total: {duracion_total/60:.2f} minutos ({duracion_total/len(df_groktest):.2f} s por fila en promedio)")

 Procesando 10.1002-14651858.CD009781.pub2 (1/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"738437d6-e6b2-fd8a-ddbe-1f175fcabe2a","object":"chat.completion","created":1762996788,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.91 s


 Procesando 10.1002-14651858.CD010694.pub2 (2/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"8c3749e0-a69b-6128-2ce7-1f84468581b7","object":"chat.completion","created":1762996822,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 38.80 s


 Procesando 10.1002-14651858.CD009416.pub2 (3/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"148a8e7d-c31b-cec2-544a-be556c8a448d","object":"chat.completion","created":1762996860,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 36.13 s


 Procesando 10.1002-14651858.CD004104.pub4 (4/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"50c32f9b-7181-3256-e369-d580d4445eaa","object":"chat.completion","created":1762996897,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.00 s


 Procesando 10.1002-14651858.CD012689.pub2 (5/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"ce539ae6-5af7-8afb-750a-6769ea051c23","object":"chat.completion","created":1762996930,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 45.71 s


 Procesando 10.1002-14651858.CD010591.pub2 (6/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"886269f4-8127-c829-555a-fbbd64c2fb7e","object":"chat.completion","created":1762996975,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 26.77 s


 Procesando 10.1002-14651858.CD001533.pub6 (7/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"bd21bd5c-787d-a069-0eb3-b0e1ba00c5da","object":"chat.completion","created":1762997002,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 34.36 s


 Procesando 10.1002-14651858.CD010237.pub2 (8/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"bc9f24f3-32b6-9385-3f9f-4bd613e9e38a","object":"chat.completion","created":1762997036,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 36.59 s


 Procesando 10.1002-14651858.CD013272 (9/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"5b19d7a6-7663-9ba0-4ae0-6fce0e82039d","object":"chat.completion","created":1762997073,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDo Co
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 32.93 s


 Procesando 10.1002-14651858.CD009487.pub3 (10/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"7632badf-bf81-322f-8144-332ea06f0bae","object":"chat.completion","created":1762997106,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 45.96 s


 Procesando 10.1002-14651858.CD004332.pub2 (11/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"be637029-91e1-c04d-aed1-3563a41abe10","object":"chat.completion","created":1762997152,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.50 s


 Procesando 10.1002-14651858.CD013757.pub2 (12/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"8048fb4c-5d47-eaaa-9c05-36fc656e87ce","object":"chat.completion","created":1762997185,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.77 s


 Procesando 10.1002-14651858.CD010294.pub2 (13/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"792e49f1-3176-1d52-c1de-4dd2ed468386","object":"chat.completion","created":1762997219,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 28.84 s


 Procesando 10.1002-14651858.CD009169.pub3 (14/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f0784cb9-f78a-9cb3-f2e1-87818caa9573","object":"chat.completion","created":1762997248,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 40.52 s


 Procesando 10.1002-14651858.CD010766.pub2 (15/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"caa7f136-391f-9fdc-97db-63cf74ae8f26","object":"chat.completion","created":1762997289,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 45.95 s


 Procesando 10.1002-14651858.CD013276.pub2 (16/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"0c383dd2-46eb-8176-53c3-96dd0e80ae42","object":"chat.completion","created":1762997334,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTools
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 84.92 s


 Procesando 10.1002-14651858.CD013206.pub2 (17/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"5b5f8b67-d970-57f2-b856-73e49684e8a5","object":"chat.completion","created":1762997419,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nCompa
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 31.63 s


 Procesando 10.1002-14651858.CD004178.pub2 (18/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"6e8da752-6281-403e-27b1-2635d3224c8d","object":"chat.completion","created":1762997451,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 35.27 s


 Procesando 10.1002-14651858.CD001808.pub3 (19/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"dd54e6ea-be3f-b62e-8d8e-bd83c261ac34","object":"chat.completion","created":1762997486,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 37.28 s


 Procesando 10.1002-14651858.CD009445.pub2 (20/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"910ef346-7961-3ca0-f7dd-cd5b00b6aae4","object":"chat.completion","created":1762997524,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nWays
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 34.44 s


 Procesando 10.1002-14651858.CD003833.pub4 (21/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"d4a1d31b-69fb-40e6-39c6-5fdb1d3ce40c","object":"chat.completion","created":1762997558,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 30.29 s


 Procesando 10.1002-14651858.CD011219.pub4 (22/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"9875edde-faea-174b-dc31-519a36884857","object":"chat.completion","created":1762997588,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 32.18 s


 Procesando 10.1002-14651858.CD006887.pub4 (23/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"b470d8ee-2f94-c6fb-280a-7fce2eabff25","object":"chat.completion","created":1762997621,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 34.10 s


 Procesando 10.1002-14651858.CD007668.pub3 (24/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"a307ad19-0c71-df3d-02c0-d020678bc287","object":"chat.completion","created":1762997655,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 37.09 s


 Procesando 10.1002-14651858.CD010512.pub2 (25/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"b5bd90f2-9d04-e3be-9166-2b5ef0c1f44a","object":"chat.completion","created":1762997692,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 42.02 s


 Procesando 10.1002-14651858.CD008872.pub2 (26/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"a1d4da2c-c30d-b85d-3104-75c22b60d500","object":"chat.completion","created":1762997734,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nCheck
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 30.54 s


 Procesando 10.1002-14651858.CD009669.pub4 (27/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f795bc91-ac9f-0cab-e6cd-8a09ce6cd5c6","object":"chat.completion","created":1762997764,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 26.89 s


 Procesando 10.1002-14651858.CD010698.pub2 (28/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"bca31912-8047-aa3e-6762-3675b91a3e18","object":"chat.completion","created":1762997791,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 40.50 s


 Procesando 10.1002-14651858.CD012280.pub2 (29/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"c1c87add-0176-5674-7a86-30d1d6ede558","object":"chat.completion","created":1762997832,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nExerc
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 31.81 s


 Procesando 10.1002-14651858.CD010322.pub2 (30/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"c2d81bee-4e28-0c2f-ce68-e9fb479746dd","object":"chat.completion","created":1762997864,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nStudy
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 43.56 s


 Procesando 10.1002-14651858.CD013067.pub2 (31/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f70c6a55-1578-f6a6-b83b-03984da56f4b","object":"chat.completion","created":1762997907,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 32.34 s


 Procesando 10.1002-14651858.CD013359.pub2 (32/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"da2a4bfc-4b8d-1d93-7a92-27df1b3256b2","object":"chat.completion","created":1762997939,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nQuick
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 35.59 s


 Procesando 10.1002-14651858.CD012852.pub2 (33/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"d758a387-d396-54f8-bd7d-158b5247c8d0","object":"chat.completion","created":1762997975,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 32.75 s


 Procesando 10.1002-14651858.CD003677.pub5 (34/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"ac21928d-06b1-06eb-b6a1-35bfa29fc84b","object":"chat.completion","created":1762998008,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nCompa
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 45.72 s


 Procesando 10.1002-14651858.CD011165.pub2 (35/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"94b5c316-7275-b2ab-8dcb-64fe008a3beb","object":"chat.completion","created":1762998053,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 36.69 s


 Procesando 10.1002-14651858.CD004242.pub5 (36/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"937d68b3-d801-2d22-a470-2311bc5b67d9","object":"chat.completion","created":1762998090,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nCompa
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.97 s


 Procesando 10.1002-14651858.CD011022.pub2 (37/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"6b38bf5a-245a-8914-aeec-bdfdd03cdc3b","object":"chat.completion","created":1762998124,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 33.70 s


 Procesando 10.1002-14651858.CD000227.pub4 (38/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"b9985f56-d237-7b90-9105-44561508daff","object":"chat.completion","created":1762998158,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 34.26 s


 Procesando 10.1002-14651858.CD001902.pub2 (39/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f904b46b-d7b8-8f0d-82db-22f3a01d0af3","object":"chat.completion","created":1762998192,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nWhen
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 36.20 s


 Procesando 10.1002-14651858.CD010502.pub2 (40/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"f53a3363-9bc0-a02c-e621-bc9de767094c","object":"chat.completion","created":1762998228,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nQuick
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 35.62 s


 Procesando 10.1002-14651858.CD013345.pub2 (41/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"6504b3b8-5361-10f7-a77a-ad8e6e0574fb","object":"chat.completion","created":1762998264,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 31.12 s


 Procesando 10.1002-14651858.CD005260.pub4 (42/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"ea5e55b1-ee0d-1def-dafb-a152fb654f14","object":"chat.completion","created":1762998295,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nTesti
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 37.13 s


 Procesando 10.1002-14651858.CD007584.pub2 (43/380)...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"a7bd229d-4dde-5a4b-e6c5-cd7ef8a6d7a0","object":"chat.completion","created":1762998332,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nRevie
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
 Tiempo de respuesta: 34.94 s


 Procesando 10.1002-14651858.CD008905.pub3 (44/380)...

Código de estado: 200

In [8]:
# Ruta del archivo csv guardado para verificar su contenido.
ruta_csv = "./results_grok2.csv"
df_check = pd.read_csv(ruta_csv)


df_check.info()

df_check.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         380 non-null    object
 1   article      380 non-null    object
 2   summary      380 non-null    object
 3   gen_summary  377 non-null    object
dtypes: object(4)
memory usage: 12.0+ KB

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,### Plain Title\nReview of Studies on Eye Drop...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,### Plain Title\nTesting if Sulodexide Medicin...
2,10.1002-14651858.CD009416.pub2,Background\r\nThere is currently no strong con...,Which treatments are effective for the treatme...,### Plain Title\nReview of Treatments for Long...
3,10.1002-14651858.CD004104.pub4,Background\r\nNon‐invasive ventilation (NIV) w...,Non‐invasive ventilation for people with respi...,### Plain Title\nTesting a Breathing Machine t...
4,10.1002-14651858.CD012689.pub2,Background\r\nSpace spraying is the dispersal ...,Insecticide space spraying for preventing mala...,### Plain Title\nDoes Spraying Insect Killer i...

In [9]:
# Ver cuántos faltan
faltante = df_check[df_check["gen_summary"].isnull()]
print(f" Faltan {len(faltante)} resúmenes.")
display(faltante[["name", "article"]])

 Faltan 3 resúmenes.

,name,article
115,10.1002-14651858.CD006173.pub2,Background\r\nAdministration of the uterotonic...
214,10.1002-14651858.CD006652.pub5,Background\r\nAnticoagulation may improve surv...
281,10.1002-14651858.CD003408.pub3,Background\r\nSince pulmonary artery balloon f...

In [10]:
# Reprocesar solo esa fila
if not faltante.empty:
    for i, fila in faltante.iterrows():
        print(f"\n Reprocesando {fila['name']}...\n")
        resumen, tiempo = call_grok_api(prompt, fila['article'])
        df_check.loc[i, "gen_summary"] = resumen if resumen else ""
        print(f"Reparado en {tiempo:.2f} s")

# Guardar nuevamente el CSV actualizado
df_check.to_csv(ruta_csv, index=False, encoding="utf-8")
print(f"Archivo actualizado: {os.path.abspath(ruta_csv)}")

 Reprocesando 10.1002-14651858.CD006173.pub2...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"878ac369-7bfa-689d-ad01-5e3c74ca6a00","object":"chat.completion","created":1763079387,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
Reparado en 49.51 s

 Reprocesando 10.1002-14651858.CD006652.pub5...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"9c5ec478-4777-11ff-28ae-ea7f4eb97df5","object":"chat.completion","created":1763079437,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nBlood
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
Reparado en 37.56 s

 Reprocesando 10.1002-14651858.CD003408.pub3...

Código de estado: 200
Respuesta (primeros 200 caracteres): {"id":"773c6f2a-4b96-ddcb-439a-47f45933de0c","object":"chat.completion","created":1763079474,"model":"grok-4-0709","choices":[{"index":0,"message":{"role":"assistant","content":"### Plain Title\nDoes
Claves en respuesta: dict_keys(['id', 'object', 'created', 'model', 'choices', 'usage', 'system_fingerprint'])
Reparado en 33.03 s
Archivo actualizado: c:\Users\braya\OneDrive\Documentos\GitHub\Proyecto-PLN-FLAG\src\api_tests\results_grok2.csv

In [11]:
# Ruta del archivo csv guardado para verificar su contenido.
ruta_csv = "./results_grok2.csv"
df_check = pd.read_csv(ruta_csv)


df_check.info()

df_check.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         380 non-null    object
 1   article      380 non-null    object
 2   summary      380 non-null    object
 3   gen_summary  380 non-null    object
dtypes: object(4)
memory usage: 12.0+ KB

,name,article,summary,gen_summary
0,10.1002-14651858.CD009781.pub2,Background\r\nTraumatic corneal abrasions are ...,Topical non‐steroidal anti‐inflammatory drugs ...,### Plain Title\nReview of Studies on Eye Drop...
1,10.1002-14651858.CD010694.pub2,"Background\r\nVenous leg ulcers are common, ch...",Sulodexide for venous leg ulcers\r\nReview que...,### Plain Title\nTesting if Sulodexide Medicin...
2,10.1002-14651858.CD009416.pub2,Background\r\nThere is currently no strong con...,Which treatments are effective for the treatme...,### Plain Title\nReview of Treatments for Long...
3,10.1002-14651858.CD004104.pub4,Background\r\nNon‐invasive ventilation (NIV) w...,Non‐invasive ventilation for people with respi...,### Plain Title\nTesting a Breathing Machine t...
4,10.1002-14651858.CD012689.pub2,Background\r\nSpace spraying is the dispersal ...,Insecticide space spraying for preventing mala...,### Plain Title\nDoes Spraying Insect Killer i...